# Generated by Django 3.0.5 on 2024-02-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('None', 'None'), ('flower_pots', 'flower_pots'), ('smoke', 'smoke'), ('sparklers', 'sparklers'), ('One Sound Crackers', 'One Sound Crackers'), ('Multi Shots', 'Multi Shots'), ('Peacock', 'Peacock'), ('Matches', 'Matches'), ('Multi Sky Shots', 'Multi Sky Shots'), ('Bijili', 'Bijili'), ('Ground Chakkars', 'Ground Chakkars')], default='None', max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
