# Generated by Django 3.0.5 on 2024-02-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20240206_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartable',
            old_name='productid',
            new_name='productid_id',
        ),
        migrations.RenameField(
            model_name='cartable',
            old_name='userid',
            new_name='userid_id',
        ),
    ]
