# Generated by Django 3.0.5 on 2024-02-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20240206_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartable',
            name='productid_id',
        ),
        migrations.AddField(
            model_name='cartable',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product'),
        ),
    ]
