# Generated by Django 3.0.5 on 2024-02-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20240206_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartable',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product'),
        ),
    ]
