# Generated by Django 3.0.5 on 2024-02-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20240206_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartable',
            name='userid_id',
        ),
        migrations.AddField(
            model_name='cartable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer'),
        ),
    ]
